# 顶层 'version' 字段已过时，可以省略
services:
  # 前端 Next.js 服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myblog-frontend
    ports:
      - "3000:3000" # 映射主机 3000 到容器 3000
    environment:
      # 后端服务的基础 URL (无端口，无末尾斜杠)
      NEXT_PUBLIC_BACKEND_URL: http://backend
      # 后端服务实际运行的端口
      NEXT_PUBLIC_PORT: 8081
      # 添加其他前端需要的环境变量...
    depends_on:
      - backend
    networks:
      - app-network

  # 后端 Koa 服务
  backend:
    build:
      context: ./backend # 指向 backend submodule 目录
      dockerfile: Dockerfile
    container_name: myblog-backend
    environment:
      NODE_ENV: production
      # 设置后端服务监听的端口
      PORT: 8081
      # 添加其他后端需要的环境变量...
    volumes:
      # 将本地的 Git 仓库目录映射到容器内的 /blog-posts
      # !!! 重要：请将下面的 /path/to/your/local/blog-repo 替换为你本地仓库的实际绝对路径 !!!
      - /Users/foril/projects/blog/blog-posts:/blog-posts:ro # 使用 :ro 表示只读挂载
    networks:
      - app-network
    # 后端端口不需要映射到主机，除非有特殊调试需求

# 自定义网络定义
networks:
  app-network:
    driver: bridge
