import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@/styles/Home.module.sass'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laborum, totam qui enim sit, nobis reiciendis reprehenderit ad vitae provident asperiores rem consequuntur alias saepe quibusdam. Hic omnis enim expedita doloremque?
            </main>
        </>
    )
}

export default Home
