import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@/styles/Home.module.sass'
import PostList from '@/components/PostList'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
              <PostList />
            </main>
        </>
    )
}

export default Home
